# https://taskfile.dev

version: '3'

tasks:
  db:up:
    desc: 🗃️ run database migrations (up)
    cmds:
      - sea migrate up
  
  db:down:
    desc: 🗃️ run database migrations (down)
    cmds:
      - sea migrate down

  run:watch:
    desc: 🚀 watch rustler
    cmds:
      - cargo watch -c -x "run --example=rustler"

  build:watch:
    desc: 🚀 watch rustler «build»
    cmds:
      - cargo watch -c -x "build"

  build:
    desc: ⚡ build rustler «release»
    cmds:
      - cargo build --release
      - python check_size.py

  fmt:
    desc: 🎨 format rustler
    cmds:
      - cargo +nightly fmt --all

  test:
    desc: 🧪 test lool
    cmds:
      - cargo nextest run --all-features --workspace

  lint:
    desc: 🧶 lint rustler
    cmds:
      - cargo clippy --fix --workspace --allow-staged