[registries.lugit]
index = "sparse+http://lugit.local/api/packages/lucodear/cargo/"

[registries.lugit-sa]
index = "sparse+http://lugit.local/api/packages/singleaction/cargo/"

[registry]
global-credential-providers = ["cargo:token"]
